apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-frame-auth-app.fullname" . }}-db
  labels:
    {{- include "pi-frame-auth-app.selectorLabels" . | nindent 6 }}-db
spec:
  selector:
    {{- include "pi-frame-auth-app.selectorLabels" . | nindent 6 }}-db
  ports:
    - protocol: TCP
      port: {{ .Values.service.db.port }}
      targetPort: {{ .Values.service.db.port }}