apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-frame-auth-app.fullname" . }}
  labels:
    {{- include "pi-frame-auth-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.webapp.type }}
  ports:
    - port: {{ .Values.service.webapp.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pi-frame-auth-app.selectorLabels" . | nindent 4 }}
