apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bookstack.fullname" . }}-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: "vsphere-storage"
status: {}
