apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "bookstack.fullname" . }}-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: "vsphere-storage"
status: {}
