apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Brett\OneDrive\Documents\kompose.exe convert -f .\bookstack.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: bookstack
  name: bookstack
spec:
  ports:
    - name: "6875"
      port: 6875
      targetPort: 80
  selector:
    io.kompose.service: bookstack
status:
  loadBalancer: {}
